spring.application.name=realtime

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.uzyaptcjsxvgptexzpik

spring.datasource.password=LSAP@9871ayu
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v2
jwt.secretkey=juyebwqd9873u3db9d1988uhdbbwooquyehjmnbscakjsdncjhfgglka8983lkajdh
